# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import svcpa.cadastro.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('date_of_birth', models.DateField(verbose_name='data de nascimento')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('cpf', models.CharField(max_length=11, validators=[svcpa.cadastro.validators.validate_cpf], verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('address', models.CharField(max_length=255, verbose_name='endereço')),
                ('neighborhood', models.CharField(max_length=20, verbose_name='bairro')),
                ('city', models.CharField(max_length=20, verbose_name='cidade')),
                ('state', models.CharField(max_length=2, verbose_name='estado')),
                ('cep', models.CharField(max_length=8, validators=[svcpa.cadastro.validators.validate_cep], verbose_name='CEP')),
                ('paid', models.BooleanField(default=False, verbose_name='pago')),
            ],
            options={
                'verbose_name': 'sócio',
                'verbose_name_plural': 'sócios',
            },
        ),
    ]
