# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import svcpa.cadastro.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AlterField(
            model_name='member',
            name='cep',
            field=models.CharField(blank=True, max_length=8, validators=[svcpa.cadastro.validators.validate_cep], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='member',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=20, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid',
            field=models.DateField(default=None, null=True, verbose_name='vencimento da anualidade'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
    ]
