# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20171202_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='paid',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='vencimento da anualidade'),
        ),
    ]
