# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20171208_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('M', 'dinheiro'), ('T', 'transferência bancária'), ('C', 'cheque')], max_length=1, verbose_name='tipo')),
                ('date', models.DateField(verbose_name='data')),
                ('value', models.FloatField(verbose_name='valor')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Member', verbose_name='sócio')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
            },
        ),
    ]
