# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20171202_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em'),
        ),
    ]
