# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.IntegerField(default='001', verbose_name='recibo nº'),
            preserve_default=False,
        ),
    ]
