# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20171202_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='paid',
        ),
    ]
