# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_payment_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_number',
            field=models.IntegerField(default=1, verbose_name='sócio número'),
            preserve_default=False,
        ),
    ]
