# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_member_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='paid',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='vencimento da anualidade'),
        ),
    ]
